global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/studio-recipe/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'studio-recipe'

  - job_name: 'flask'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'recipe-flask'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'recipe-server'
